# Generated by Django 2.0.1 on 2018-01-20 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=63, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=127, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('display', models.ImageField(default='images/default.png', upload_to='images/')),
                ('public', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.Category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=63)),
                ('state', models.CharField(max_length=63)),
                ('zipcode', models.IntegerField()),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('building_size', models.IntegerField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, max_length=31, null=True)),
                ('description', models.TextField(blank=True, max_length=4047, null=True)),
                ('listing', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spec', to='listings.Listing')),
            ],
        ),
    ]
