# Generated by Django 2.0.1 on 2018-01-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20180120_1539'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='listing',
            unique_together=set(),
        ),
    ]
